import {
  Home,
  LiveTv,
  Apple,
  BluetoothAudio,
  AccessAlarmsRounded,
  // BabyChangingStation,
  Cable,
  YouTube,
  LanOutlined,
  Kayaking,
  Gamepad,
  Sailing,
  Hail,
  Dangerous,
  AddToDriveRounded,
  KeyboardAltSharp,
  // MicOutlined,
  Lan,
  // PaletteTwoTone,
  // AccessAlarm,
} from "@mui/icons-material";

export const category = [
  { id: 1, name: "New", icon: <Home /> },
  { id: 2, name: "Movie", icon: <LiveTv /> },
  { id: 3, name: "Animals", icon: <Apple /> },
  { id: 4, name: "Fashion", icon: <BluetoothAudio /> },
  { id: 5, name: "Musics", icon: <AccessAlarmsRounded /> },
  { id: 6, name: "Cartoon", icon: <AddToDriveRounded /> },
  { id: 7, name: "Animation", icon: <Cable /> },
  { id: 8, name: "Adventure", icon: <YouTube /> },
  { id: 9, name: "Hotels", icon: <LanOutlined /> },
  { id: 10, name: "Electrical", icon: <Kayaking /> },
  { id: 11, name: "Moderation", icon: <Gamepad /> },
  { id: 12, name: "Challenge", icon: <Sailing /> },
  { id: 13, name: "Day", icon: <Hail /> },
  { id: 14, name: "Mountain", icon: <Dangerous /> },
  { id: 15, name: "Decoration", icon: <AddToDriveRounded /> },
  { id: 16, name: "Austronaut", icon: <KeyboardAltSharp /> },
  { id: 17, name: "Bear", icon: <Lan /> },
  // { id: 2, name: "Yard", icon: <PaletteTwoTone /> },
  // { id: 1, name: "Road", icon: <MicOutlined /> },
  // { id: 2, name: "Actor", icon: <AccessAlarm /> },
];
